setwd("D:/jurna metop")
install.packages("tidyverse")
install.packages("readxl")
install.packages("writexl")
install.packages("dplyr")
library('tidyverse')
library('readxl')
dat<-read_excel('data var.xlsx')
library('dplyr')
reg1<-lm(X~y,data=dat)
summary(reg1)
